name: Test Pelican Installation on macOS via Curl

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install curl wget

      - name: Run install script
        run: curl -fsSL https://pelicanplatform.org/get-pelican/ | /bin/sh -s

      - name: Verify Pelican installation
        run: pelican --version
